### PR TITLE
Add PavanBhat to the list of contributors

### PR DESCRIPTION
**Pull request by Euphoria99**

### CODE REVIEW

**Comment by Euphoria99** [comment]
The changes have been made, I have added my name to the contributors list.

**Review by NS007-dev — COMMENTED** [review]
You have closed the pr, please can you reopen it @Euphoria99

**Comment by Euphoria99** [comment]
I have already  submitted a new PR #160 . Am i still missing something ?

**Comment by NS007-dev** [comment]
Sorry for the confusion. We have to wait for a maintainer to merge the pr. I have approved on the other. Thank you @Euphoria99

**Pull request closed without merging**
