### PR TITLE
Added My Name

### PR DESCRIPTION
**Pull request by NS007-dev**
I added my name.
Thank you.

### CODE REVIEW

**Comment by NS007-dev** [comment]
I also improved the readme.md.

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@CodingSpecies thank you for contributing. 
@all-contributors add @CodingSpecies for content.

**Comment by NS007-dev** [comment]
Thank you, is it possible for me to join this organisation please?

**Comment by NS007-dev** [comment]
#110

**Pull request merged**
