### PR TITLE
Add Manvi Jha to contributors

### PR DESCRIPTION
**Pull request by Severus-Matthew**

### CODE REVIEW

**Comment by MRslimcoder** [comment]
@Severus-Matthew your PR contains some conflicts please resolved them so that we can merge.

**Comment by Severus-Matthew** [comment]
@MRslimcoder Thanks for your review, The required changes have been done in a new PR.

**Comment by MRslimcoder** [comment]
@Severus-Matthew your new PR is merged.

**Comment by Severus-Matthew** [comment]
@MRslimcoder Thanks a lot☺

**Pull request closed without merging**
