### PR TITLE
Add my-Anas Khan to the list of contributors

### PR DESCRIPTION
**Pull request by anaskhan28**

### CODE REVIEW

**Comment by NS007-dev** [comment]
@anaskhan28 you have conflicts and also please can you correct the spelling of the word myself in your description thank you

**Comment by anaskhan28** [comment]
I don't understand everything looks fine

**Comment by NS007-dev** [comment]
@anaskhan28 you have fixed it now with this commit https://github.com/devcreatives/first_contribution/pull/117/commits/cb8d596a0a97b0c8338480d4fd5f3b2993f3a2f2 
thank you.

**Comment by anaskhan28** [comment]
then why it's giving this merging is blocked

**Comment by NS007-dev** [comment]
This is because someone needs to approve, and only the owner can merge @anaskhan28

**Review by NS007-dev — APPROVED** [review]

**Comment by NS007-dev** [comment]
I just approved, but as I am not an owner, I can not merge this. @anaskhan28  thank you.

**Comment by NS007-dev** [comment]
If you have any more questions, feel free to ask

**Comment by anaskhan28** [comment]
okay thanks, yeah I am new to GitHub

**Comment by anaskhan28** [comment]
I'll ask questions in the process of learning.

**Comment by aayush89890** [comment]
Hi @CodingSpecies how can I become a member of this community?

**Comment by NS007-dev** [comment]
> Hi @CodingSpecies how can I become a member of this community?

@aayush89890 all you have to do is fork and clone this repo, go to `Data` then to `member.json`. Add to the file with your own details, make pull request. Now you have contributed, open an issue, asking to join the organisation. Hope that helped. Any more questions, feel free to ask, thanks.

**Comment by aayush89890** [comment]
> @aayush89890 all you have to do is fork and clone this repo, go to Data then to member.json. Add to the file with your own details, make pull request. Now you have contributed, open an issue, asking to join the organisation. Hope that helped. Any more questions, feel free to ask, thanks.

Thanks @CodingSpecies . I have already raised a PR once it is merged I will open an issue.

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@all-contributors add @aayush89890 for content.

**Pull request merged**
