### PR TITLE
Update member.json

### PR DESCRIPTION
**Pull request by iamzaidsoomro**
Zaid Ahmed added

### CODE REVIEW

**Review by NS007-dev — CHANGES_REQUESTED** [review]
Please can you remove the comma on line 496

**Comment by iamzaidsoomro** [comment]
@CodingSpecies removed the comma

**Review by NS007-dev — APPROVED** [review]

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@all-contributors add @iamzaidsoomro for content.

**Pull request merged**
