### PR TITLE
Add my-name to the list of contributors

### PR DESCRIPTION
**Pull request by ankyBot**
that's my first-time contribution, please accept my pull request.

### CODE REVIEW

**Review by NS007-dev — CHANGES_REQUESTED** [review]
@ankyBot please can you move your info to the bottom of the file? This is because the oldest entries go to the top, and the newest go at the bottom. Thank you.

**Review by NS007-dev — APPROVED** [review]
LGTM thanks for contributing @ankyBot

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@all-contributors add @ankyBot for content.

**Pull request merged**
