### PR TITLE
Add own name (Brandon_Gui123) to the list of contributions

### PR DESCRIPTION
**Pull request by Brandon-Gui123**
Hello! In this PR, I added my own name to `Data/member.json`, following the format in that file.

### CODE REVIEW

**Review by NS007-dev — CHANGES_REQUESTED** [review]
I think, as your LinkedIn is empty, I would remove that. Thank you @Brandon-Gui123

**Comment by Brandon-Gui123** [comment]
> 
> 
> I think, as your LinkedIn is empty, I would remove that. Thank you @Brandon-Gui123

To clarify, is it the removal of the `"linkedinurl"` property? If so, I think this suggestion should be better taken to the owners, since I noticed that many users who don't have a LinkedIn URL left it with an empty string.

**Comment by NS007-dev** [comment]
> > I think, as your LinkedIn is empty, I would remove that. Thank you @Brandon-Gui123
> 
> To clarify, is it the removal of the `"linkedinurl"` property? If so, I think this suggestion should be better taken to the owners, since I noticed that many users who don't have a LinkedIn URL left it with an empty string.

Yes, I think your right, it might break the code, and if others have done that, then that's fine. Sorry for that @Brandon-Gui123 . Thank you.

**Review by NS007-dev — APPROVED** [review]

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@Brandon-Gui123 can you please resolve conflicts so that we can merge your PR.

**Comment by Brandon-Gui123** [comment]
@MRslimcoder Ok I fixed the conflict. I simply rebased my branch and moved my name all the way so that it is the last one.

Feel free to let me know if there are any other problems!

**Comment by Brandon-Gui123** [comment]
Sorry for the sudden change to draft, since I myself forgot how rebasing works and didn't realize that I have supplied the wrong commit message. I've already corrected the message and we should be good to go!

**Comment by MrSlimCoder** [comment]
@Brandon-Gui123 Hi can please again fix conflicts.. We merge top PR's first.

**Comment by Brandon-Gui123** [comment]
Ok, I fixed the conflict.

**Review by MrSlimCoder — APPROVED** [review]

**Comment by MrSlimCoder** [comment]
@Brandon-Gui123 The PR is dead we can't merge you have to send another one.

**Pull request closed without merging**
