### PR TITLE
Add Aleksey-Voko to the list of contributors

### PR DESCRIPTION
**Pull request by Aleksey-Voko**
@Aleksey-Voko

### CODE REVIEW

**Review by NS007-dev — APPROVED** [review]
Thank you for contributing @Aleksey-Voko !

**Comment by Aleksey-Voko** [comment]
Should someone review and approve?

**Comment by NS007-dev** [comment]
Yes @Aleksey-Voko as I am not a maintainer we will have to wait. 
thank you

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@all-contributors add @Aleksey-Voko for code.

**Comment by Aleksey-Voko** [comment]
Thanks!

**Pull request merged**
