### PR TITLE
Add my-name to the list of contributors

### PR DESCRIPTION
**Pull request by shadow-prince**

### CODE REVIEW

**Comment by AvidCoder101** [comment]
Thanks for your contribution @shadow-prince. @MRslimcoder I think that this PR can be merged now? By the way @shadow-prince Next time, I would recommend that you add a description as it is good practice and provides the reviewers with info about the PR.

**Review by AvidCoder101 — APPROVED** [review]
LGTM

**Review by MrSlimCoder — APPROVED** [review]
LGTM

**Comment by MrSlimCoder** [comment]
@all-contributors add @shadow-prince for content.

**Pull request merged**
